UdemyUplift/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UdemyUplift.DataAccess.Data.Repository.Interfaces;
using UdemyUplift.Models;

namespace UdemyUplift.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            var category = new Category();
            if(id == null)
            {
                return View(category);
            }

            category = _unitOfWork.Category.Get(id.GetValueOrDefault());
            if(category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if(category.Id == 0)
                {
                    _unitOfWork.Category.Add(category);
                }
                else
                {
                    _unitOfWork.Category.Update(category);
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAllCategories()
        {
            return Json(new { data = _unitOfWork.Category.GetAll()});
        }

        [HttpDelete]
        public IActionResult DeleteCategory(int id)
        {
            var objFromDatabase = _unitOfWork.Category.Get(id);
            if(objFromDatabase == null)
            {
                return Json(new { success = false, message = "Error while deleting. Category with specified ID does not exist." });
            }

            _unitOfWork.Category.Remove(objFromDatabase);
            _unitOfWork.Save();

            return Json(new { success = true, message = $"Object with ID {objFromDatabase.DisplayOrder} removed succesfully" });
        }

        #endregion
    }
}

UdemyUplift/Areas/Admin/Controllers/FrequencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UdemyUplift.DataAccess.Data.Repository.Interfaces;
using UdemyUplift.Models;

namespace UdemyUplift.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FrequencyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public FrequencyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            var frequency = new Frequency();
            if(id == null)
            {
                return View(frequency);

            }

            frequency = _unitOfWork.Frequency.Get(id.GetValueOrDefault());
            if(frequency == null)
            {
                return NotFound();
            }

            return View(frequency);
        }

        #region API Calls

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Frequency frequency)
        {
            if(ModelState.IsValid)
            {
                if(frequency.Id == 0)
                {
                    _unitOfWork.Frequency.Add(frequency);
                }
                else
                {
                    _unitOfWork.Frequency.Update(frequency);
                }

                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(frequency);
        }

        [HttpGet]
        public IActionResult GetAllFrequencies() => Json(new { data = _unitOfWork.Frequency.GetAll() });

        [HttpDelete]
        public IActionResult DeleteFrequency(int id)
        {
            var objFromDatabase = _unitOfWork.Frequency.Get(id);
            if(objFromDatabase == null)
            {
                return Json(new { success = false, message = "Could not find such frequency" });
            }

            _unitOfWork.Frequency.Remove(objFromDatabase);
            _unitOfWork.Save();

            return Json(new { success = true, message = $"Successfully deleted Frequency named {objFromDatabase.Name}. " });
        }
        
        #endregion
    }
}

UdemyUplift/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UdemyUplift.Models;

namespace UdemyUplift.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UdemyUplift/Areas/Admin/Views/Category/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="border backgroundWhite">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Upsert" class="btn btn-primary"><i class="fas fa-plus"> &nbsp; Create New Category</i></a>
        </div>
    </div>

    <br />
    <br />
    <table id="tblData" class="table table-striped table-boareded" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Display Order</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{ 
<script src="~/js/category.js"></script>
}

UdemyUplift/Areas/Admin/Views/Category/Upsert.cshtml
@model UdemyUplift.Models.Category

@{
    var title = "Create category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Upsert">

    <div class="row px-2 mx-2 backgroundWhite border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if(Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
            title = "Edit Category";
        }
        <div class="col-12">
            <h2 class="text-primary">@title</h2>
            <br />
        </div>
        <div class="col-8">
            
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="DisplayOrder"></label>
                </div>
                <div class="col-8">
                    <input asp-for="DisplayOrder" class="form-control" />
                    <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    @if (Model.Id != 0)
                    {
                        //Edit and back to list
                        <partial name="_EditAndBackToListButton" model="Model.Id" />
                    }
                    else
                    {
                        //Create and back to list
                        <partial name="_CreateAndBackToListButton" />
                    }
                </div>
            </div>
        </div>
    </div>
</form>

UdemyUplift/Areas/Admin/Views/Frequency/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="border backgroundWhite">
    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Frequency List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Upsert" class="btn btn-primary"><i class="fas fa-plus">&nbsp; Create New Frequency</i></a>
        </div>
    </div>

    <br />
    <br />

    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Frequency count</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
       <script src="~/js/frequency.js"></script>
}

UdemyUplift/Areas/Admin/Views/Frequency/Upsert.cshtml
@model UdemyUplift.Models.Frequency
@{
    var title = "Create Frequency";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" asp-action="Upsert">
    <div class="row px-2 mx-2 backgroundWhite border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if(Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
            title = "Edit Frequency";
        }

        <div class="col-12">
            <h2 class="text-primary">@title</h2>
            <br />
        </div>
        <div class="col-8">


            <div class="form-group">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-4">
                    <label asp-for="FrequencyCount"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FrequencyCount" class="form-control" />
                    <span asp-validation-for="FrequencyCount" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-8 offset-4">
                    @if(Model.Id != 0)
                    {
                        <partial name="_EditAndBackToListButton" model="Model.Id" />
                    }
                    else
                    {
                        <partial name="_CreateAndBackToListButton" />
                    }
                </div>
            </div>
        </div>
    </div>
</form>

UdemyUplift/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UdemyUplift/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button> 
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

UdemyUplift/Views/Shared/_EditAndBackToListButton.cshtml
@model int

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
        </div>
        <div class="col">
            <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
        </div>
    </div>

UdemyUplift/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UdemyUplift</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">UdemyUplift</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarColor01"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">

                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li>
                        <div class="dropdown show">

                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" id="navbarDropDown" data-toggle="dropdown" aria-haspopup="true" area-expanded="false">
                                Content Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Frequency" asp-action="Index">Frequency</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Service" asp-action="Index">Service</a>
                            </div>
                        </div>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container my-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - UdemyUplift - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/a234c60ff3.js" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>